-- Phase 1: tạo bảng thường (chưa partition, chưa index tối ưu)
-- Dùng để lấy execution plan BEFORE optimization.

DROP TABLE IF EXISTS order_item CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS order_item_unoptimized CASCADE;
DROP TABLE IF EXISTS order_unoptimized CASCADE;

CREATE TABLE "order" (
    order_id      integer GENERATED BY DEFAULT AS IDENTITY,
    customer_id   integer NOT NULL,
    order_date    timestamp NOT NULL,
    status        varchar(20) NOT NULL,
    total_amount  numeric(12,2) NOT NULL DEFAULT 0,
    created_at    timestamp NOT NULL,

    CONSTRAINT pk_order PRIMARY KEY (order_id),
    CONSTRAINT fk_order_customer
        FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
    CONSTRAINT ck_order_status
        CHECK (status IN ('PLACED', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED')),
    CONSTRAINT ck_order_total_amount
        CHECK (total_amount >= 0),
    CONSTRAINT ck_order_created_at
        CHECK (created_at >= order_date)
);

CREATE TABLE order_item (
    order_item_id bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id      integer NOT NULL,
    product_id    integer NOT NULL,
    order_date    timestamp NOT NULL,
    quantity      integer NOT NULL,
    unit_price    numeric(12,2) NOT NULL,
    subtotal      numeric(12,2) NOT NULL,
    created_at    timestamp NOT NULL,

    CONSTRAINT pk_order_item PRIMARY KEY (order_item_id),
    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id) REFERENCES "order"(order_id),
    CONSTRAINT fk_order_item_product
        FOREIGN KEY (product_id) REFERENCES product(product_id),
    CONSTRAINT ck_order_item_quantity
        CHECK (quantity > 0),
    CONSTRAINT ck_order_item_unit_price
        CHECK (unit_price > 0),
    CONSTRAINT ck_order_item_subtotal
        CHECK (subtotal = quantity * unit_price),
    CONSTRAINT ck_order_item_created_at
        CHECK (created_at >= order_date)
);
