-- Phase 2: chuyển dữ liệu sang bảng partition theo tháng và tạo index.
-- PostgreSQL yêu cầu PRIMARY KEY/UNIQUE trên partitioned table phải chứa partition key.
-- Vì vậy PK được đổi thành (order_id, order_date) và
-- (order_item_id, order_date); FK order_item -> order cũng dùng cặp cột này.

ALTER TABLE order_item RENAME TO order_item_unoptimized;
ALTER TABLE "order" RENAME TO order_unoptimized;

CREATE TABLE "order" (
    order_id      integer GENERATED BY DEFAULT AS IDENTITY,
    customer_id   integer NOT NULL,
    order_date    timestamp NOT NULL,
    status        varchar(20) NOT NULL,
    total_amount  numeric(12,2) NOT NULL DEFAULT 0,
    created_at    timestamp NOT NULL,

    CONSTRAINT pk_order_partitioned PRIMARY KEY (order_id, order_date),
    CONSTRAINT fk_order_customer_partitioned
        FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
    CONSTRAINT ck_order_status_partitioned
        CHECK (status IN ('PLACED', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED')),
    CONSTRAINT ck_order_total_amount_partitioned
        CHECK (total_amount >= 0),
    CONSTRAINT ck_order_created_at_partitioned
        CHECK (created_at >= order_date)
) PARTITION BY RANGE (order_date);

CREATE TABLE order_2025_01 PARTITION OF "order"
FOR VALUES FROM ('2025-01-01') TO ('2025-02-01');
CREATE TABLE order_2025_02 PARTITION OF "order"
FOR VALUES FROM ('2025-02-01') TO ('2025-03-01');
CREATE TABLE order_2025_03 PARTITION OF "order"
FOR VALUES FROM ('2025-03-01') TO ('2025-04-01');
CREATE TABLE order_2025_04 PARTITION OF "order"
FOR VALUES FROM ('2025-04-01') TO ('2025-05-01');
CREATE TABLE order_2025_05 PARTITION OF "order"
FOR VALUES FROM ('2025-05-01') TO ('2025-06-01');
CREATE TABLE order_default PARTITION OF "order" DEFAULT;

CREATE TABLE order_item (
    order_item_id bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id      integer NOT NULL,
    product_id    integer NOT NULL,
    order_date    timestamp NOT NULL,
    quantity      integer NOT NULL,
    unit_price    numeric(12,2) NOT NULL,
    subtotal      numeric(12,2) NOT NULL,
    created_at    timestamp NOT NULL,

    CONSTRAINT pk_order_item_partitioned PRIMARY KEY (order_item_id, order_date),
    CONSTRAINT fk_order_item_order_partitioned
        FOREIGN KEY (order_id, order_date)
        REFERENCES "order"(order_id, order_date),
    CONSTRAINT fk_order_item_product_partitioned
        FOREIGN KEY (product_id) REFERENCES product(product_id),
    CONSTRAINT ck_order_item_quantity_partitioned
        CHECK (quantity > 0),
    CONSTRAINT ck_order_item_unit_price_partitioned
        CHECK (unit_price > 0),
    CONSTRAINT ck_order_item_subtotal_partitioned
        CHECK (subtotal = quantity * unit_price),
    CONSTRAINT ck_order_item_created_at_partitioned
        CHECK (created_at >= order_date)
) PARTITION BY RANGE (order_date);

CREATE TABLE order_item_2025_01 PARTITION OF order_item
FOR VALUES FROM ('2025-01-01') TO ('2025-02-01');
CREATE TABLE order_item_2025_02 PARTITION OF order_item
FOR VALUES FROM ('2025-02-01') TO ('2025-03-01');
CREATE TABLE order_item_2025_03 PARTITION OF order_item
FOR VALUES FROM ('2025-03-01') TO ('2025-04-01');
CREATE TABLE order_item_2025_04 PARTITION OF order_item
FOR VALUES FROM ('2025-04-01') TO ('2025-05-01');
CREATE TABLE order_item_2025_05 PARTITION OF order_item
FOR VALUES FROM ('2025-05-01') TO ('2025-06-01');
CREATE TABLE order_item_default PARTITION OF order_item DEFAULT;

-- Migrate dữ liệu.
INSERT INTO "order" (
    order_id, customer_id, order_date, status, total_amount, created_at
)
SELECT
    order_id, customer_id, order_date, status, total_amount, created_at
FROM order_unoptimized;

INSERT INTO order_item (
    order_item_id, order_id, product_id, order_date,
    quantity, unit_price, subtotal, created_at
)
SELECT
    order_item_id, order_id, product_id, order_date,
    quantity, unit_price, subtotal, created_at
FROM order_item_unoptimized;

-- Đồng bộ identity sequences sau khi chèn ID có sẵn.
SELECT setval(
    pg_get_serial_sequence('"order"', 'order_id'),
    (SELECT max(order_id) FROM "order"),
    true
);

SELECT setval(
    pg_get_serial_sequence('order_item', 'order_item_id'),
    (SELECT max(order_item_id) FROM order_item),
    true
);

-- Index bắt buộc theo đề và các index hỗ trợ report/join.
CREATE INDEX idx_order_item_product_id
    ON order_item(product_id);

CREATE INDEX idx_order_item_order_id_date
    ON order_item(order_id, order_date);

CREATE INDEX idx_order_status_date
    ON "order"(status, order_date);

CREATE INDEX idx_order_total_amount_desc
    ON "order"(total_amount DESC);

CREATE INDEX IF NOT EXISTS idx_product_seller_product
    ON product(seller_id, product_id);

CREATE INDEX IF NOT EXISTS idx_product_brand_product
    ON product(brand_id, product_id);

CREATE INDEX IF NOT EXISTS idx_product_category_product
    ON product(category_id, product_id);

ANALYZE "order";
ANALYZE order_item;
ANALYZE product;

-- Kiểm tra partition routing.
SELECT
    tableoid::regclass AS partition_name,
    count(*) AS row_count
FROM "order"
GROUP BY tableoid
ORDER BY partition_name::text;

SELECT
    tableoid::regclass AS partition_name,
    count(*) AS row_count
FROM order_item
GROUP BY tableoid
ORDER BY partition_name::text;
