"""
Project 03 - Python in Data (PostgreSQL version)

Generate synthetic E-commerce OLTP data using Faker and load it into
PostgreSQL. The generated schema is compatible with Project 04.

Required Project 04 base tables:
    brand, category, seller, customer, product,
    promotion, promotion_product
"""

from __future__ import annotations

import os
import random
from collections.abc import Iterable, Iterator, Sequence
from datetime import timedelta
from typing import Any

import psycopg2
from dotenv import load_dotenv
from faker import Faker
from psycopg2.extensions import connection as PgConnection
from psycopg2.extras import execute_values


load_dotenv()


def env_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None or value.strip() == "":
        return default
    try:
        parsed = int(value)
    except ValueError as exc:
        raise ValueError(f"{name} must be an integer, received: {value!r}") from exc
    if parsed <= 0:
        raise ValueError(f"{name} must be greater than 0")
    return parsed


def env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


DB_CONFIG = {
    "host": os.getenv("DB_HOST", "localhost"),
    "port": env_int("DB_PORT", 5432),
    "dbname": os.getenv("DB_NAME", "ecommerce"),
    "user": os.getenv("DB_USER", "postgres"),
    "password": os.getenv("DB_PASSWORD", ""),
}

BRAND_COUNT = env_int("BRAND_COUNT", 20)
SELLER_COUNT = env_int("SELLER_COUNT", 25)
CUSTOMER_COUNT = env_int("CUSTOMER_COUNT", 10_000)
PRODUCT_COUNT = env_int("PRODUCT_COUNT", 2_000)
PROMOTION_COUNT = env_int("PROMOTION_COUNT", 10)
PROMOTION_PRODUCT_COUNT = env_int("PROMOTION_PRODUCT_COUNT", 100)
BATCH_SIZE = env_int("BATCH_SIZE", 5_000)
RESET_SCHEMA = env_bool("RESET_SCHEMA", True)

fake = Faker()
random.seed(42)
Faker.seed(42)


DDL_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS brand (
        brand_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        brand_name VARCHAR(100) NOT NULL,
        country    VARCHAR(50),
        created_at TIMESTAMP NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS category (
        category_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category_name      VARCHAR(100) NOT NULL,
        parent_category_id INTEGER,
        level              SMALLINT NOT NULL CHECK (level IN (1, 2)),
        created_at         TIMESTAMP NOT NULL,
        CONSTRAINT fk_category_parent
            FOREIGN KEY (parent_category_id) REFERENCES category(category_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS seller (
        seller_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        seller_name VARCHAR(150) NOT NULL,
        join_date   DATE NOT NULL,
        seller_type VARCHAR(50) NOT NULL,
        rating      NUMERIC(2,1) NOT NULL CHECK (rating BETWEEN 0 AND 5),
        country     VARCHAR(50) NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS customer (
        customer_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        customer_name VARCHAR(150) NOT NULL,
        email         VARCHAR(180) NOT NULL UNIQUE,
        phone         VARCHAR(20),
        join_date     DATE NOT NULL,
        country       VARCHAR(50) NOT NULL,
        created_at    TIMESTAMP NOT NULL,
        is_active     BOOLEAN NOT NULL DEFAULT TRUE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS product (
        product_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_name   VARCHAR(200) NOT NULL,
        category_id    INTEGER NOT NULL,
        brand_id       INTEGER NOT NULL,
        seller_id      INTEGER NOT NULL,
        price          NUMERIC(12,2) NOT NULL CHECK (price > 0),
        discount_price NUMERIC(12,2) NOT NULL
            CHECK (discount_price > 0 AND discount_price <= price),
        stock_qty      INTEGER NOT NULL CHECK (stock_qty >= 0),
        rating         NUMERIC(2,1) NOT NULL CHECK (rating BETWEEN 0 AND 5),
        created_at     TIMESTAMP NOT NULL,
        is_active      BOOLEAN NOT NULL,
        CONSTRAINT fk_product_category
            FOREIGN KEY (category_id) REFERENCES category(category_id),
        CONSTRAINT fk_product_brand
            FOREIGN KEY (brand_id) REFERENCES brand(brand_id),
        CONSTRAINT fk_product_seller
            FOREIGN KEY (seller_id) REFERENCES seller(seller_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS promotion (
        promotion_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        promotion_name VARCHAR(100) NOT NULL,
        promotion_type VARCHAR(50) NOT NULL,
        discount_type  VARCHAR(20) NOT NULL
            CHECK (discount_type IN ('percentage', 'fixed_amount')),
        discount_value NUMERIC(10,2) NOT NULL CHECK (discount_value > 0),
        start_date     DATE NOT NULL,
        end_date       DATE NOT NULL,
        CONSTRAINT ck_promotion_dates CHECK (end_date >= start_date)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS promotion_product (
        promo_product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        promotion_id     INTEGER NOT NULL,
        product_id       INTEGER NOT NULL,
        created_at       TIMESTAMP NOT NULL,
        CONSTRAINT fk_promotion_product_promotion
            FOREIGN KEY (promotion_id) REFERENCES promotion(promotion_id),
        CONSTRAINT fk_promotion_product_product
            FOREIGN KEY (product_id) REFERENCES product(product_id),
        CONSTRAINT uq_promotion_product UNIQUE (promotion_id, product_id)
    )
    """,
]

DROP_STATEMENTS = [
    "DROP TABLE IF EXISTS promotion_product CASCADE",
    "DROP TABLE IF EXISTS promotion CASCADE",
    "DROP TABLE IF EXISTS product CASCADE",
    "DROP TABLE IF EXISTS customer CASCADE",
    "DROP TABLE IF EXISTS seller CASCADE",
    "DROP TABLE IF EXISTS category CASCADE",
    "DROP TABLE IF EXISTS brand CASCADE",
]


def generate_brands(n: int) -> Iterator[tuple[Any, ...]]:
    for _ in range(n):
        yield fake.company(), fake.country(), fake.date_time_this_decade()


def generate_categories() -> list[tuple[Any, ...]]:
    main_categories = [
        "Electronics",
        "Fashion",
        "Home & Living",
        "Sports",
        "Beauty",
    ]
    sub_categories = {
        "Electronics": "Mobile Phones",
        "Fashion": "Men's Clothing",
        "Home & Living": "Kitchen",
        "Sports": "Outdoor Gear",
        "Beauty": "Skincare",
    }

    rows: list[tuple[Any, ...]] = []
    for name in main_categories:
        rows.append((name, None, 1, fake.date_time_this_year()))
    for parent_name, sub_name in sub_categories.items():
        rows.append((sub_name, parent_name, 2, fake.date_time_this_year()))
    return rows


def generate_sellers(n: int) -> Iterator[tuple[Any, ...]]:
    seller_types = ["Official", "Marketplace"]
    for _ in range(n):
        yield (
            fake.company(),
            fake.date_between(start_date="-5y", end_date="today"),
            random.choice(seller_types),
            round(random.uniform(3, 5), 1),
            "Vietnam",
        )


def generate_customers(n: int) -> Iterator[tuple[Any, ...]]:
    """Generate deterministic unique emails so large runs do not collide."""
    for i in range(1, n + 1):
        created_at = fake.date_time_between(start_date="-5y", end_date="now")
        yield (
            fake.name(),
            f"customer_{i:07d}@example.com",
            "0" + "".join(str(random.randint(0, 9)) for _ in range(9)),
            created_at.date(),
            "Vietnam",
            created_at,
            random.random() < 0.95,
        )


def generate_products(
    n: int,
    brand_ids: Sequence[int],
    category_ids: Sequence[int],
    seller_ids: Sequence[int],
) -> Iterator[tuple[Any, ...]]:
    for _ in range(n):
        price = round(random.uniform(100_000, 50_000_000), 2)
        discount_price = round(price * random.uniform(0.7, 1.0), 2)
        created_at = fake.date_time_between(start_date="-3y", end_date="now")
        yield (
            fake.catch_phrase(),
            random.choice(category_ids),
            random.choice(brand_ids),
            random.choice(seller_ids),
            price,
            discount_price,
            random.randint(0, 500),
            round(random.uniform(3, 5), 1),
            created_at,
            random.choice([True, False]),
        )


def generate_promotions(n: int) -> Iterator[tuple[Any, ...]]:
    promotion_types = ["product", "category", "seller", "flash_sale", "bundle"]
    discount_types = ["percentage", "fixed_amount"]
    base_names = [
        "Mega Sale",
        "Super Sale",
        "Year-End Clearance",
        "Flash Friday",
        "Summer Deals",
        "Tet Holiday Sale",
        "Back to School",
        "Double Day",
        "VIP Member Week",
        "Brand Festival",
    ]

    for i in range(n):
        start = fake.date_between(start_date="-2y", end_date="today")
        end = start + timedelta(days=random.randint(30, 50))
        discount_type = random.choice(discount_types)
        discount_value = (
            round(random.uniform(5, 30), 2)
            if discount_type == "percentage"
            else round(random.uniform(10_000, 200_000), 2)
        )
        yield (
            f"{base_names[i % len(base_names)]} #{i + 1}",
            random.choice(promotion_types),
            discount_type,
            discount_value,
            start,
            end,
        )


def generate_promotion_products(
    n: int,
    promotion_ids: Sequence[int],
    product_ids: Sequence[int],
) -> Iterator[tuple[Any, ...]]:
    max_pairs = len(promotion_ids) * len(product_ids)
    if n > max_pairs:
        raise ValueError(
            f"PROMOTION_PRODUCT_COUNT={n} exceeds the maximum unique pairs {max_pairs}"
        )

    pairs: set[tuple[int, int]] = set()
    while len(pairs) < n:
        pairs.add((random.choice(promotion_ids), random.choice(product_ids)))

    for promotion_id, product_id in pairs:
        yield promotion_id, product_id, fake.date_time_this_year()


def batched(rows: Iterable[tuple[Any, ...]], batch_size: int) -> Iterator[list[tuple[Any, ...]]]:
    batch: list[tuple[Any, ...]] = []
    for row in rows:
        batch.append(row)
        if len(batch) >= batch_size:
            yield batch
            batch = []
    if batch:
        yield batch


def bulk_insert(
    conn: PgConnection,
    table_label: str,
    sql: str,
    rows: Iterable[tuple[Any, ...]],
    batch_size: int = BATCH_SIZE,
) -> int:
    inserted = 0
    with conn.cursor() as cur:
        for batch in batched(rows, batch_size):
            execute_values(cur, sql, batch, page_size=len(batch))
            inserted += len(batch)
            print(f"   {table_label:<20} {inserted:>10,} rows", end="\r")
    conn.commit()
    print(f"   {table_label:<20} {inserted:>10,} rows")
    return inserted


def fetch_ids(conn: PgConnection, table: str, id_column: str) -> list[int]:
    with conn.cursor() as cur:
        cur.execute(f"SELECT {id_column} FROM {table} ORDER BY {id_column}")
        return [row[0] for row in cur.fetchall()]


def prepare_schema(conn: PgConnection) -> None:
    with conn.cursor() as cur:
        if RESET_SCHEMA:
            # Avoid silently damaging an existing Project 04 database.
            cur.execute(
                """
                SELECT
                    to_regclass('public.\"order\"') IS NOT NULL,
                    to_regclass('public.order_item') IS NOT NULL
                """
            )
            order_exists, order_item_exists = cur.fetchone()
            if order_exists or order_item_exists:
                raise RuntimeError(
                    "Project 04 tables already exist. Use a fresh PostgreSQL database, "
                    "or drop Project 04 tables before RESET_SCHEMA=true."
                )

            print("▶ Resetting Project 03 schema...")
            for statement in DROP_STATEMENTS:
                cur.execute(statement)

        print("▶ Creating PostgreSQL tables...")
        for statement in DDL_STATEMENTS:
            cur.execute(statement)
    conn.commit()


def insert_categories(conn: PgConnection) -> list[int]:
    rows = generate_categories()
    level1 = [row for row in rows if row[2] == 1]
    level2 = [row for row in rows if row[2] == 2]

    bulk_insert(
        conn,
        "category level 1",
        """
        INSERT INTO category
            (category_name, parent_category_id, level, created_at)
        VALUES %s
        """,
        level1,
    )

    with conn.cursor() as cur:
        cur.execute(
            "SELECT category_id, category_name FROM category WHERE level = 1"
        )
        parent_ids = {name: category_id for category_id, name in cur.fetchall()}

    resolved_level2 = [
        (name, parent_ids[parent_name], level, created_at)
        for name, parent_name, level, created_at in level2
    ]
    bulk_insert(
        conn,
        "category level 2",
        """
        INSERT INTO category
            (category_name, parent_category_id, level, created_at)
        VALUES %s
        """,
        resolved_level2,
    )
    return fetch_ids(conn, "category", "category_id")


def validate_counts(conn: PgConnection) -> None:
    tables = [
        "brand",
        "category",
        "seller",
        "customer",
        "product",
        "promotion",
        "promotion_product",
    ]
    print("\n✅ Project 03 data is ready for Project 04:")
    with conn.cursor() as cur:
        for table in tables:
            cur.execute(f"SELECT COUNT(*) FROM {table}")
            count = cur.fetchone()[0]
            print(f"   {table:<20} {count:>10,} rows")

        cur.execute("SELECT COUNT(*) FROM product WHERE price > 0")
        valid_products = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM customer")
        customers = cur.fetchone()[0]

    if customers == 0 or valid_products < 5:
        raise RuntimeError(
            "Project 04 precheck will fail: customer must be non-empty and at "
            "least five products must have price > 0."
        )


def main() -> None:
    conn: PgConnection | None = None
    try:
        print(
            f"▶ Connecting to PostgreSQL {DB_CONFIG['host']}:{DB_CONFIG['port']} "
            f"database={DB_CONFIG['dbname']}..."
        )
        conn = psycopg2.connect(**DB_CONFIG)
        prepare_schema(conn)

        print("▶ Inserting brand...")
        bulk_insert(
            conn,
            "brand",
            """
            INSERT INTO brand (brand_name, country, created_at)
            VALUES %s
            """,
            generate_brands(BRAND_COUNT),
        )
        brand_ids = fetch_ids(conn, "brand", "brand_id")

        print("▶ Inserting category...")
        category_ids = insert_categories(conn)

        print("▶ Inserting seller...")
        bulk_insert(
            conn,
            "seller",
            """
            INSERT INTO seller
                (seller_name, join_date, seller_type, rating, country)
            VALUES %s
            """,
            generate_sellers(SELLER_COUNT),
        )
        seller_ids = fetch_ids(conn, "seller", "seller_id")

        print("▶ Inserting customer...")
        bulk_insert(
            conn,
            "customer",
            """
            INSERT INTO customer
                (customer_name, email, phone, join_date, country, created_at, is_active)
            VALUES %s
            """,
            generate_customers(CUSTOMER_COUNT),
        )

        print("▶ Inserting product...")
        bulk_insert(
            conn,
            "product",
            """
            INSERT INTO product
                (product_name, category_id, brand_id, seller_id, price,
                 discount_price, stock_qty, rating, created_at, is_active)
            VALUES %s
            """,
            generate_products(
                PRODUCT_COUNT,
                brand_ids=brand_ids,
                category_ids=category_ids,
                seller_ids=seller_ids,
            ),
        )
        product_ids = fetch_ids(conn, "product", "product_id")

        print("▶ Inserting promotion...")
        bulk_insert(
            conn,
            "promotion",
            """
            INSERT INTO promotion
                (promotion_name, promotion_type, discount_type, discount_value,
                 start_date, end_date)
            VALUES %s
            """,
            generate_promotions(PROMOTION_COUNT),
        )
        promotion_ids = fetch_ids(conn, "promotion", "promotion_id")

        print("▶ Inserting promotion_product...")
        bulk_insert(
            conn,
            "promotion_product",
            """
            INSERT INTO promotion_product
                (promotion_id, product_id, created_at)
            VALUES %s
            """,
            generate_promotion_products(
                PROMOTION_PRODUCT_COUNT,
                promotion_ids=promotion_ids,
                product_ids=product_ids,
            ),
        )

        validate_counts(conn)
        print("\nNext: run Project04_SQL/00_precheck.sql in the same database.")

    except Exception as exc:
        if conn is not None:
            conn.rollback()
        print(f"\n❌ Failed: {exc}")
        raise
    finally:
        if conn is not None:
            conn.close()


if __name__ == "__main__":
    main()
